services:
  auth_service:
    build: ./
    container_name: auth_module
    ports:
      - 5000:5000
    env_file:
      - .docker.env
    volumes:
      - ./:/auth
      - /auth/node_modules
    restart: unless-stopped
    command: yarn dev
