services:
  content_module_db_service:
    image: mysql:lts-oraclelinux9
    container_name: content_module_db_container
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: content_module_db
      MYSQL_PASSWORD: '0000'
      MYSQL_USER: fadi
    volumes:
      - content_module_db-data:/var/lib/mysql

  content_module_admin_service:
    image: phpmyadmin:fpm-alpine
    container_name: content_module_db_admin
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      PMA_HOST: content_module_db_service
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - content_module_db_admin:/var/lib/mysql
    depends_on:
      - content_module_db_service

  content_service:
    build: .
    container_name: content_module
    ports:
      - 5004:5004
      - 5555:5555
    env_file:
      - .docker.env
    restart: always
    volumes:
      - ./:/content
      - /content/node_modules
    links:
      - content_module_db_service
    command: yarn dev

volumes:
  content_module_db-data:
  content_module_db_admin:
